name: live_chat_messenger
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  google_sign_in:
  shared_preferences:
  random_string:
  cloud_firestore: ^3.4.3
  google_fonts: 
 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  
  flutter_launcher_icons: 

flutter_icons:
  android: true
  image_path: "assets/App Icon.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  adaptive_icon_background: "#ffffff"
  
flutter:
  uses-material-design: true
  assets: 
    - assets/google-logo.png
    - assets/App Icon.png
    - assets/AppIconTransparent.png
    - assets/userProfile.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
